[features]
seeds = true
[programs.localnet]
staking = "EMVNZcM6epTkxfCcjxqv44aXNcaaPArLGAjxjMWfjsoy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
